package com.maraloedev.Ejercicios;

import com.maraloedev.clases.Productos;
import com.maraloedev.clases.TiposProductos;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Ejercicio01_Almacen extends javax.swing.JFrame {

    //Modelos lista y combo
    static DefaultListModel modeloLista = new DefaultListModel();
    static DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();

    //Conexiones base de datos
    static String url = "jdbc:mysql://localhost:3306/almacen";
    static String user = "root";
    static String pasword = "";
    static PreparedStatement ps;
    static ResultSet rs;

    static Productos p;
    static TiposProductos tp;
    static int tipoProducto;

    /**
     * Creates new form Ejercicio01_Almacen
     */
    public Ejercicio01_Almacen() {
        initComponents();
        setFrame();
        components();
    }

    private void setFrame() {
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void components() {
        tiposProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboProductos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setDisplayedMnemonic('A');
        jLabel1.setText("Tipo producto:");

        comboProductos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProductosItemStateChanged(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de productos"));

        listaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProductosItemStateChanged
        listaProductos();
    }//GEN-LAST:event_comboProductosItemStateChanged

    private void listaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaProductosMouseClicked
        cantidadProductos();
    }//GEN-LAST:event_listaProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio01_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio01_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio01_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio01_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ejercicio01_Almacen().setVisible(true);
        });
    }

    private Connection conexionBD() throws SQLException {
        return DriverManager.getConnection(url, user, pasword);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaProductos;
    // End of variables declaration//GEN-END:variables

    private void tiposProductos() {
        comboProductos.setModel(modeloCombo);
        modeloCombo.addElement("(elige uno)");
        try (Connection conn = conexionBD()) {
            ps = conn.prepareStatement("SELECT * FROM tiposproducto");
            rs = ps.executeQuery();

            while (rs.next()) {
                int idTipo = rs.getInt("idTipo");
                Character tipo = rs.getString("tipo").charAt(0);

                tp = new TiposProductos(idTipo, tipo);
                modeloCombo.addElement(tp);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ejercicio01_Almacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void listaProductos() {
        listaProductos.setModel(modeloLista);
        modeloLista.clear();
        try (Connection conn = conexionBD()) {
            ps = conn.prepareStatement("SELECT * FROM productos WHERE tipo = ?");

            String itemSeleccionado = modeloCombo.getSelectedItem().toString();

            if (itemSeleccionado.contains(("(elige uno)"))) {
                JOptionPane.showMessageDialog(null, "Elige un producto");
                return;
            }

            tipoProducto = 0;

            switch (itemSeleccionado) {
                case "A":
                    tipoProducto = 1;
                    break;
                case "B":
                    tipoProducto = 2;
                    break;
                case "C":
                    tipoProducto = 3;
                default:
                    JOptionPane.showMessageDialog(null, "tipo no encontrado");
            }

            ps.setInt(1, tipoProducto);

            rs = ps.executeQuery();

            while (rs.next()) {
                int idProducto = rs.getInt("idProducto");
                String descripcion = rs.getString("descripcion");
                Double precio = rs.getDouble("precio");
                int cantidad = rs.getInt("cantidad");
                int tipo = rs.getInt("tipo");
                p = new Productos(idProducto, descripcion, precio, cantidad, tipo);
                modeloLista.addElement(p);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ejercicio01_Almacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cantidadProductos() {

        try (Connection conn = conexionBD()) {
            ps = conn.prepareStatement("SELECT cantidad FROM productos");

            rs = ps.executeQuery();

            if (rs.next()) {

                 int cantidad = rs.getInt("cantidad");
                p.setCantidad(cantidad);

                if (cantidad <= 10) {
                    JOptionPane.showMessageDialog(null, "Nº unidades:" + cantidad + "\nDebajo del stock de seguridad", "Stock en almacén", JOptionPane.WARNING_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Nº unidades:" + cantidad, "Stock en almacén", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ejercicio01_Almacen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
