/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.maraloedev.Ejercicios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class Ejercicio02_Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio02_Usuarios
     */
    static final String URL = "jdbc:mysql://localhost:3306/usuarios";
    static final String USER = "root";
    static final String PASSWORD = "";

    static PreparedStatement ps;
    static ResultSet rs;

    static int intentos = 1;

    public Ejercicio02_Usuarios() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        setTitle("Login");
        setResizable(false);
        setLocationRelativeTo(null);
        repeticionPass.setVisible(false);
        passRepeat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        Borrar = new javax.swing.JButton();
        Entrar = new javax.swing.JButton();
        usuarioIntroducido = new javax.swing.JTextField();
        contrasenaIntroducida = new javax.swing.JPasswordField();
        registro = new javax.swing.JLabel();
        repeticionPass = new javax.swing.JLabel();
        passRepeat = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        User.setText("Usuario:");

        password.setText("Contraseña:");

        Borrar.setText("Borrar todo");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Entrar.setText("Validar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });

        registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registro.setForeground(new java.awt.Color(0, 0, 204));
        registro.setText("<html><u>¿Todavia no te has registrado?</html></u>");
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroMouseClicked(evt);
            }
        });

        repeticionPass.setText("Confirmacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Borrar)
                                .addGap(36, 36, 36)
                                .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(repeticionPass)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(passRepeat))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(password)
                                    .addGap(18, 18, 18)
                                    .addComponent(contrasenaIntroducida))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(User)
                                    .addGap(38, 38, 38)
                                    .addComponent(usuarioIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User)
                    .addComponent(usuarioIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(contrasenaIntroducida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repeticionPass)
                    .addComponent(passRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        if (passRepeat.isVisible() && repeticionPass.isVisible()) {
            registroUsuario();
        } else {
            comprobacionUsuario();
        }
    }//GEN-LAST:event_EntrarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        usuarioIntroducido.setText("");
        contrasenaIntroducida.setText("");

        repeticionPass.setVisible(false);
        passRepeat.setVisible(false);
        registro.setVisible(true);
    }//GEN-LAST:event_BorrarActionPerformed

    private void registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseClicked
        registroUsuario();
    }//GEN-LAST:event_registroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio02_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ejercicio02_Usuarios().setVisible(true);
        });
    }

    private Connection conexionBD() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    private void comprobacionUsuario() {
        try (Connection conn = conexionBD()) {

            ps = conn.prepareStatement(
                    "SELECT * "
                    + "FROM usuario "
                    + "WHERE login = ? AND password = ?");

            String usuario = usuarioIntroducido.getText();
            String pass = new String(contrasenaIntroducida.getPassword());

            // Doy valor a los ?
            ps.setString(1, usuario);
            ps.setString(2, pass);

            rs = ps.executeQuery();

            if (rs.next()) {
                setTitle("Conectado");
            } else {
                JOptionPane.showMessageDialog(null, "Procede al registro\n Intentos " + intentos++);

                if (intentos == 3) {
                    ps = conn.prepareStatement(
                            "UPDATE usuario "
                            + "SET blocked = 1 "
                            + "WHERE login = ?");
                    
                    ps.setString(1, usuario);
                    
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Cuenta bloqueada");
                    intentos = 0;
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Ejercicio02_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void registroUsuario() {
        repeticionPass.setVisible(true);
        passRepeat.setVisible(true);
        registro.setVisible(false);

        String nuevoUsuario = usuarioIntroducido.getText();
        String password1 = new String(contrasenaIntroducida.getPassword());
        String password2 = new String(passRepeat.getPassword());

        if (!nuevoUsuario.isEmpty() && password1.length() > 0) {
            if (password1.equals(password2)) {
                try (Connection con = conexionBD()) {
                    PreparedStatement ps = con.prepareStatement(
                            "INSERT INTO usuario (login, password, blocked) VALUES (?, ?, ?)"
                    );
                    ps.setString(1, nuevoUsuario);
                    ps.setString(2, password1);
                    ps.setInt(3, 0);

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Usuario agregado");
                } catch (SQLException ex) {
                    Logger.getLogger(Ejercicio02_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuario y contraseña no pueden estar vacíos");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Entrar;
    private javax.swing.JLabel User;
    private javax.swing.JPasswordField contrasenaIntroducida;
    private javax.swing.JPasswordField passRepeat;
    private javax.swing.JLabel password;
    private javax.swing.JLabel registro;
    private javax.swing.JLabel repeticionPass;
    private javax.swing.JTextField usuarioIntroducido;
    // End of variables declaration//GEN-END:variables
}
