package Ejercicios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Eduardo
 */
public class Problema2 extends javax.swing.JFrame {

    /**
     * Creates new form Problema2
     */
    static String url = "jdbc:mysql://localhost:3306/carnetdb";
    static String user = "root";
    static String password = "";
    static PreparedStatement ps;
    static ResultSet rs;
    static ArrayList<Carnet> listaCarnets = new ArrayList<>();

    public Problema2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaCarnets = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        creacionC = new javax.swing.JMenu();
        crearCarnets = new javax.swing.JMenuItem();
        buscarC = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mostrarC = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaCarnets.setEditable(false);
        areaCarnets.setColumns(20);
        areaCarnets.setRows(5);
        jScrollPane1.setViewportView(areaCarnets);

        creacionC.setText("Crear");

        crearCarnets.setText("Carnets");
        crearCarnets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCarnetsActionPerformed(evt);
            }
        });
        creacionC.add(crearCarnets);

        jMenuBar1.add(creacionC);

        buscarC.setText("Buscar");

        jMenuItem1.setText("Por titular");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        buscarC.add(jMenuItem1);

        jMenuBar1.add(buscarC);

        mostrarC.setText("Mostrar");
        jMenuBar1.add(mostrarC);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCarnetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCarnetsActionPerformed
        crearCarnets();
    }//GEN-LAST:event_crearCarnetsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        buscarTitular();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void crearCarnets() {
        boolean crear = true;
        try (Connection conn = coneBD()) {
            ps = conn.prepareStatement("SELECT * FROM carnet");
            rs = ps.executeQuery();

            while (rs.next()) {
                listaCarnets.add(new Carnet(rs.getInt("codigo"), rs.getString("titular"), rs.getInt("puntos")));
                crear = true;
            }

            if (crear) {
                JOptionPane.showMessageDialog(null, "Carnets almacenados en la lista");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Problema2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void buscarTitular() {
        areaCarnets.removeAll();
        String nombreTitular = JOptionPane.showInputDialog(null, "Introcuzca el nombre del usuario a buscar");
        boolean encontrado = false;

        for (Carnet c : listaCarnets) {
            if (nombreTitular.contains(c.getTitular())) {
                areaCarnets.setText("Los puntos de " + nombreTitular + " son de " + c.getPuntos() + " puntos");
                encontrado = true;
            }
        }

        if (!encontrado) {
            System.out.println(encontrado);
            areaCarnets.setText("No se a encontrado ningun carnet con ese nombre");
        }
    }

    private Connection coneBD() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Problema2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaCarnets;
    private javax.swing.JMenu buscarC;
    private javax.swing.JMenu creacionC;
    private javax.swing.JMenuItem crearCarnets;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mostrarC;
    // End of variables declaration//GEN-END:variables

}
