package com.maraloedev.examenseptiembre;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Ejercicio2 extends javax.swing.JFrame {

    static ArrayList<Prenda> listaPrendas = new ArrayList<>();
    static DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
        setTitle("Problema 2");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCrearPrendas = new javax.swing.JButton();
        botonMostrarPrendas = new javax.swing.JButton();
        botonOrdenarPrendas = new javax.swing.JButton();
        botonBuscarPorColor = new javax.swing.JButton();
        botonTotalPrendas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPrendas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonCrearPrendas.setText("Crear Pendas");
        botonCrearPrendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPrendasActionPerformed(evt);
            }
        });

        botonMostrarPrendas.setText("Mostrar prendas");
        botonMostrarPrendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarPrendasActionPerformed(evt);
            }
        });

        botonOrdenarPrendas.setText("Ordenar Prendas");

        botonBuscarPorColor.setText("Buscar por color");
        botonBuscarPorColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPorColorActionPerformed(evt);
            }
        });

        botonTotalPrendas.setText("Total Prendas");
        botonTotalPrendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTotalPrendasActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListaPrendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCrearPrendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonOrdenarPrendas, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(botonBuscarPorColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonTotalPrendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMostrarPrendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botonCrearPrendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonMostrarPrendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonOrdenarPrendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscarPorColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonTotalPrendas)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearPrendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPrendasActionPerformed
        listaPrendas.add(new Prenda("Camiseta manga corta", 'S', "Blanco", 5.99));
        listaPrendas.add(new Prenda("Pantalon vaquero", 'M', "Azul", 30));
        listaPrendas.add(new Prenda("Camiseta dibujo", 'M', "Amarillo", 10));
        listaPrendas.add(new Prenda("Vestido largo flores ", 'S', "Varios", 50));

        JOptionPane.showMessageDialog(null, "Prendas creadas correctamente");
        botonCrearPrendas.setEnabled(false);
    }//GEN-LAST:event_botonCrearPrendasActionPerformed

    private void botonMostrarPrendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarPrendasActionPerformed
        listModel.clear();
        ListaPrendas.setModel(listModel);

        listModel.addElement("DESCRIPCIÓN | TALLA | COLOR | PRECIO");

        for (Prenda mostrarPrendas : listaPrendas) {
            listModel.addElement(String.valueOf(mostrarPrendas));
        }
        botonCrearPrendas.setEnabled(false);
    }//GEN-LAST:event_botonMostrarPrendasActionPerformed

    private void botonBuscarPorColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPorColorActionPerformed
        String seleccionColor = JOptionPane.showInputDialog(null, "Introduce el nombre a buscar:");
        listModel.clear();
        
        listModel.addElement("Prendas de color " + seleccionColor);
        boolean encontrado = true;
        for (Prenda colorSeleccionado : listaPrendas) {
            if(seleccionColor.equals(colorSeleccionado.getColor())) {
                listModel.addElement(colorSeleccionado.getDescripcion());
                encontrado = false;
            }
            }
            if(encontrado) {
                JOptionPane.showMessageDialog(null, "Color no encontrado", "Informacion", JOptionPane.ERROR_MESSAGE);
               
        }
    }//GEN-LAST:event_botonBuscarPorColorActionPerformed

    private void botonTotalPrendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTotalPrendasActionPerformed
        int total =0;
        
        for(Prenda precioTotal : listaPrendas) {
            total+=precioTotal.getPrecio();
        }
        
        JOptionPane.showMessageDialog(null, "El precio total de las prendas es de " + total);
    }//GEN-LAST:event_botonTotalPrendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaPrendas;
    private javax.swing.JButton botonBuscarPorColor;
    private javax.swing.JButton botonCrearPrendas;
    private javax.swing.JButton botonMostrarPrendas;
    private javax.swing.JButton botonOrdenarPrendas;
    private javax.swing.JButton botonTotalPrendas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
