/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.maraloedev.tema9.layouts;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JButton;

/**
 *
 * @author macarena
 * 
 * En este ejemplo la asignaci�n del layout no se hace desde la vista Design en la ventana Navigator, 
 * sino en c�digo con el m�todo setLayout. 
 */
public class EjemploGridBag_2 extends javax.swing.JFrame {

    
    public EjemploGridBag_2() {
        initComponents();
        this.getContentPane().setLayout(new GridBagLayout());
        crearBotones();
    }

    private void crearBotones() {
        JButton boton1 = new JButton("Uno");
        GridBagConstraints r1=new GridBagConstraints();
        //colocación del botón
        r1.gridx=0;
        r1.gridy=0;
//        llenamos espacios en su celda
        r1.fill=GridBagConstraints.BOTH; 
        //le damos doble anchura
        r1.gridwidth=2;
        //expandimos celdas en vertical y horizontal
        r1.weightx=1;
        r1.weighty=1;        
        
        JButton boton2 = new JButton("Dos");
        GridBagConstraints r2=new GridBagConstraints();
        r2.gridx=2;
        r2.gridy=0;
        r2.fill=GridBagConstraints.BOTH; 
        r2.weightx=1;
        r2.weighty=1;
        
        JButton boton3 = new JButton("Tres");
        GridBagConstraints r3=new GridBagConstraints();
        r3.gridx=3;
        r3.gridy=0;
        r3.fill=GridBagConstraints.BOTH;
        r3.weightx=1;
        r3.weighty=1;
        
        JButton boton4 = new JButton("Cuatro");
        GridBagConstraints r4=new GridBagConstraints();
        r4.gridx=0;
        r4.gridy=1;
        r4.fill=GridBagConstraints.BOTH; 
        //doble altura
        r4.gridheight=2;
        r4.weightx=1;
        r4.weighty=1;
        
        JButton boton5 = new JButton("Cinco");
        GridBagConstraints r5=new GridBagConstraints();
        r5.gridx=2;
        r5.gridy=1;
        r5.fill=GridBagConstraints.BOTH; 
        r5.gridwidth=2;
        r5.weightx=1;
        r5.weighty=1;
        
        JButton boton6 = new JButton("Seis");
        GridBagConstraints r6=new GridBagConstraints();
        r6.gridx=2;
        r6.gridy=2;
        r6.fill=GridBagConstraints.BOTH; 
        r6.gridwidth=2;
        r6.weightx=1;
        r6.weighty=1;
        
        this.getContentPane().add(boton1,r1);
        this.getContentPane().add(boton3,r3);
        this.getContentPane().add(boton4,r4);
        this.getContentPane().add(boton5,r5);
        this.getContentPane().add(boton6,r6);
        this.getContentPane().add(boton2,r2);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploGridBag_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploGridBag_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploGridBag_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploGridBag_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploGridBag_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
