/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.maraloedev.tema9.layouts;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JButton;

/**
 *
 * @author macarena
 * 
 * En vista Design desde la ventana Navigator, asignamos sobre el JFrame (bot�n derecho - set layout)
 * el layout de tipo 'Border'
 */
public class EjemploBorder extends javax.swing.JFrame {

    public EjemploBorder() {
        initComponents();
        JButton bN=new JButton("Botón norte");
        bN.setPreferredSize(new Dimension(100,100));
        JButton bS=new JButton("Botón sur");
        JButton bE=new JButton("Botón este");
        JButton bO=new JButton("Botón oeste");
        JButton bC=new JButton("Botón centro");
        
        //metemos los botones en el panel de contexto del JFrame
        this.getContentPane().add(bN, BorderLayout.PAGE_START);
        this.getContentPane().add(bS, BorderLayout.PAGE_END);
        this.getContentPane().add(bE, BorderLayout.LINE_START);
        this.getContentPane().add(bO, BorderLayout.LINE_END);
        this.getContentPane().add(bC, BorderLayout.CENTER);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploBorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploBorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploBorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploBorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploBorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
