/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.maraloedev.tema9.layouts;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JButton;

/**
 *
 * @author macarena
 * 
 * En este ejemplo la asignaci�n del layout no se hace desde la vista Design en la ventana Navigator, 
 * sino en c�digo con el m�todo setLayout. 
 */
public class EjemploGridBag extends javax.swing.JFrame {

    public EjemploGridBag() {
        initComponents();
        this.getContentPane().setLayout(new GridBagLayout());
        crearBotones();
    }

    private void crearBotones() {
        javax.swing.JButton botonN = new JButton("Boton Norte");
        GridBagConstraints restrN = new GridBagConstraints();
        //posicion
        restrN.gridx = 1;
        restrN.gridy = 0;
        //expandir el botón para que llene el espacio no ocupado de la celda
//        restrN.fill=GridBagConstraints.HORIZONTAL;    
        //estiramos la celda en vertical hasta ocupar el espacio de la ventana
//        restrN.weighty=1.0;
        //estiramos la celda en horizontal hasta ocupar el espacio de la ventana
//        restrN.weightx=1.0;
        this.getContentPane().add(botonN, restrN);

        javax.swing.JButton botonO = new JButton("Boton Oeste");
        GridBagConstraints restrO = new GridBagConstraints();
        restrO.gridx = 0;
        restrO.gridy = 1;
        this.getContentPane().add(botonO, restrO);

        javax.swing.JButton botonC = new JButton("Boton Centro");
        GridBagConstraints restrC = new GridBagConstraints();
        restrC.gridx = 01;
        restrC.gridy = 1;
        this.getContentPane().add(botonC, restrC);

        javax.swing.JButton botonE = new JButton("Boton Este");
        GridBagConstraints restrE = new GridBagConstraints();
        restrE.gridx = 2;
        restrE.gridy = 1;
        this.getContentPane().add(botonE, restrE);
        
        javax.swing.JButton botonS = new JButton("Boton Sur");
        GridBagConstraints restrS = new GridBagConstraints();
        restrS.gridx = 1;
        restrS.gridy = 2;
        restrS.fill=GridBagConstraints.HORIZONTAL;   
        this.getContentPane().add(botonS, restrS);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploGridBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploGridBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploGridBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploGridBag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploGridBag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
