/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.maraloedev.tema9.Ejercicios;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvValidationException;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Eduardo
 */
public class EjercicioEncuesta extends javax.swing.JFrame {

    static File archivo = new File("encuesta.csv");
    static String[] cabecera = {"Si", "No", "NS-NC"};
    static int votoSi = 0;
    static int votoNo = 0;
    static int votoNsNc = 0;

    /**
     * Creates new form EjercicioEncuesta
     */
    public EjercicioEncuesta() {
        initComponents();
        setFrame();
    }

    public void setFrame() {
        setResizable(false);
        setTitle("Encuesta");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Si = new javax.swing.JRadioButton();
        No = new javax.swing.JRadioButton();
        NS_NC = new javax.swing.JRadioButton();
        Votar = new javax.swing.JButton();
        ResultadosEncuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 102, 204));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("¿Te gustaría realizar las practicas en la modalidad FP DUAL?");

        GrupoBotones.add(Si);
        Si.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Si.setSelected(true);
        Si.setText("Si");

        GrupoBotones.add(No);
        No.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        No.setText("No");

        GrupoBotones.add(NS_NC);
        NS_NC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NS_NC.setText("NS/NC");

        Votar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Votar.setForeground(new java.awt.Color(255, 0, 51));
        Votar.setText("Votar");
        Votar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VotarMouseClicked(evt);
            }
        });

        ResultadosEncuesta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResultadosEncuesta.setForeground(new java.awt.Color(255, 0, 51));
        ResultadosEncuesta.setText("Resultados de la encuesta");
        ResultadosEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadosEncuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(No)
                                    .addComponent(Si)
                                    .addComponent(NS_NC)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Votar, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ResultadosEncuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Si)
                .addGap(18, 18, 18)
                .addComponent(No)
                .addGap(18, 18, 18)
                .addComponent(NS_NC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Votar)
                .addGap(18, 18, 18)
                .addComponent(ResultadosEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VotarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VotarMouseClicked
        try (CSVWriter csvw = new CSVWriter(new FileWriter(archivo))) {
            csvw.writeNext(cabecera);

            Enumeration<AbstractButton> botones = GrupoBotones.getElements();
            AbstractButton boton;

            while (botones.hasMoreElements()) { //Mientras haya mas elementos
                boton = botones.nextElement();
                if (boton.isSelected()) {
                    if (boton.getText().equals("Si")) {
                        votoSi++;
                    } else if (boton.getText().equals("No")) {
                        votoNo++;
                    } else if (boton.getText().equals("NS/NC")) {
                        votoNsNc++;
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar una opcion");
                    }
                }
            }

            JOptionPane.showMessageDialog(null, "Voto almacenado correctamente");
            String[] votos = {String.valueOf(votoSi), String.valueOf(votoNo), String.valueOf(votoNsNc)};
            csvw.writeNext(votos);

        } catch (IOException ex) {
            Logger.getLogger(EjercicioEncuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VotarMouseClicked

    private void ResultadosEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadosEncuestaActionPerformed
//        try(CSVReader cSVReader = new CSVReader(new FileReader(archivo))) {
//            
//            String[] linea = null;
//            
//            while((linea = cSVReader.readNext())!=null) {
//                JOptionPane.showMessageDialog(null, Arrays.toString(linea));
//            }
//            
//            
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(EjercicioEncuesta.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException | CsvValidationException ex) {
//            Logger.getLogger(EjercicioEncuesta.class.getName()).log(Level.SEVERE, null, ex);
//        }

try (CSVReader cSVReader = new CSVReader(new FileReader(archivo))) {
        
        // Obtener fecha y hora actual
        LocalDateTime ahora = LocalDateTime.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String fechaHora = ahora.format(formato);

        // Construir el mensaje
        StringBuilder mensaje = new StringBuilder();
        mensaje.append("Fecha y hora: ").append(fechaHora).append("\n\n");

        String[] linea;

        while ((linea = cSVReader.readNext()) != null) {
            for (String campo : linea) {
                mensaje.append(campo).append("  "); // Puedes cambiar el separador si quieres
            }
            mensaje.append("\n");
        }

        // Mostrar mensaje en una ventana con scroll
        JTextArea areaTexto = new JTextArea(mensaje.toString());
        areaTexto.setEditable(false);
        areaTexto.setFont(new java.awt.Font("Monospaced", Font.PLAIN, 12));

        JScrollPane scroll = new JScrollPane(areaTexto);
        scroll.setPreferredSize(new java.awt.Dimension(500, 400));

        JOptionPane.showMessageDialog(null, scroll, "Resultados de Encuesta", JOptionPane.INFORMATION_MESSAGE);

    } catch (FileNotFoundException ex) {
        Logger.getLogger(EjercicioEncuesta.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Archivo no encontrado");
    } catch (IOException | CsvValidationException ex) {
        Logger.getLogger(EjercicioEncuesta.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Error al leer el archivo");
    }
    }//GEN-LAST:event_ResultadosEncuestaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        archivo.delete();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EjercicioEncuesta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.JRadioButton NS_NC;
    private javax.swing.JRadioButton No;
    private javax.swing.JButton ResultadosEncuesta;
    private javax.swing.JRadioButton Si;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton Votar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
