package com.maraloedev.tema9.Ejercicios;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvValidationException;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.TextArea;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;

public class Ejercicio_Encuestas extends javax.swing.JFrame {

    static int contadorSi;
    static int contadorNo;
    static int contadorNsNc;
    static File f = new File("encuesta.csv");

    /**
     * Creates new form Ejercicio_Encuestas
     */
    public Ejercicio_Encuestas() {
        initComponents();
        setFrame();
        componentes();
    }

    private void setFrame() {
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void componentes() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesOpciones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnSi = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnNsNc = new javax.swing.JRadioButton();
        btnVotar = new javax.swing.JButton();
        btnVerEncuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("<html><u>¿Quieres hacer practicas en FP DUAL?</u></html>");

        botonesOpciones.add(btnSi);
        btnSi.setSelected(true);
        btnSi.setText("Si");

        botonesOpciones.add(btnNo);
        btnNo.setText("No");

        botonesOpciones.add(btnNsNc);
        btnNsNc.setText("NS/NC");

        btnVotar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVotar.setForeground(new java.awt.Color(255, 0, 51));
        btnVotar.setText("Votar");
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });

        btnVerEncuesta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerEncuesta.setForeground(new java.awt.Color(255, 0, 51));
        btnVerEncuesta.setText("Ver Encuesta");
        btnVerEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEncuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNsNc))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnVotar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerEncuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnSi)
                .addGap(18, 18, 18)
                .addComponent(btnNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNsNc)
                .addGap(18, 18, 18)
                .addComponent(btnVotar)
                .addGap(18, 18, 18)
                .addComponent(btnVerEncuesta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        conteoVotaciones();
    }//GEN-LAST:event_btnVotarActionPerformed

    private void btnVerEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEncuestaActionPerformed
        resultadoEncuesta();
    }//GEN-LAST:event_btnVerEncuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_Encuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_Encuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_Encuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_Encuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ejercicio_Encuestas().setVisible(true);
        });
    }

    private void conteoVotaciones() {
        Enumeration<AbstractButton> seleccionOpciones = botonesOpciones.getElements();
        AbstractButton boton;

        while (seleccionOpciones.hasMoreElements()) {
            boton = seleccionOpciones.nextElement();

            if (boton.isSelected()) {
                if (boton.getText().equals("Si")) {
                    contadorSi++;
                } else if (boton.getText().equals("No")) {
                    contadorNo++;
                } else if (boton.getText().equals("NS/NC")) {
                    contadorNsNc++;
                }
            }

            btnVerEncuesta.setEnabled(true);
        }

        //Escibir
        try (CSVWriter cSVWriter = new CSVWriter(new FileWriter(f))) {

            String[] encabezado = {"Si,No,NS/NC"};
            String[] puntuaciones = {String.valueOf(contadorSi), String.valueOf(contadorNo), String.valueOf(contadorNsNc)};
            cSVWriter.writeNext(encabezado);
            cSVWriter.writeNext(puntuaciones);

        } catch (IOException ex) {
            Logger.getLogger(Ejercicio_Encuestas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resultadoEncuesta() {

        JFrame resultadosEncuesta = new JFrame("Resultados");
        JPanel panelVotos = new JPanel();

        panelVotos.setSize(new Dimension(800, 800));
        panelVotos.setLayout(new BorderLayout());

        resultadosEncuesta.add(panelVotos);
        resultadosEncuesta.setSize(new Dimension(500, 500));
        JTextArea votos = new JTextArea();
        votos.setEditable(false);

        //LEER EL CSV
        try (CSVReader csvReader = new CSVReader(new FileReader(f))) {
            String[] linea;
            StringBuilder texto = new StringBuilder();

            while ((linea = csvReader.readNext()) != null) {
                if (linea.length >= 3) {
                    texto.append(
                            "Si= ").append(linea[0]).append(": ").append(
                            "No:").append(linea[1]).append(":").append(
                            "NS/NC ").append(linea[2]);
                }
            }

            votos.setText(texto.toString());

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ejercicio_Encuestas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(Ejercicio_Encuestas.class.getName()).log(Level.SEVERE, null, ex);
        }

        panelVotos.add(votos);

        resultadosEncuesta.setVisible(true);

        if (resultadosEncuesta.isVisible()) {
            btnVerEncuesta.setEnabled(false);
        }

        resultadosEncuesta.setResizable(false);
        resultadosEncuesta.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonesOpciones;
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JRadioButton btnNsNc;
    private javax.swing.JRadioButton btnSi;
    private javax.swing.JButton btnVerEncuesta;
    private javax.swing.JButton btnVotar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
