/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Problema2;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class Problema2 extends javax.swing.JFrame {

    /**
     * Creates new form Problema2
     */
    static ArrayList<Prenda> listaPrenda = new ArrayList<>();
    static DefaultListModel modeloLista = new DefaultListModel();

    public Problema2() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPrendas = new javax.swing.JList<>();
        crearPrendas = new javax.swing.JButton();
        mostrarPrendas = new javax.swing.JButton();
        ordenarPrendas = new javax.swing.JButton();
        buscarPorColor = new javax.swing.JButton();
        totalPrendas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Problema2");

        jScrollPane1.setViewportView(listaPrendas);

        crearPrendas.setText("CREAR PRENDAS");
        crearPrendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPrendasActionPerformed(evt);
            }
        });

        mostrarPrendas.setText("MOSTRAR PRENDAS");
        mostrarPrendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPrendasActionPerformed(evt);
            }
        });

        ordenarPrendas.setText("ORDENAR PRENDAS");

        buscarPorColor.setText("BUSCAR POR COLOR");
        buscarPorColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorColorActionPerformed(evt);
            }
        });

        totalPrendas.setText("TOTAL PRENDAS");
        totalPrendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPrendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ordenarPrendas)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(crearPrendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mostrarPrendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buscarPorColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPrendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(crearPrendas)
                .addGap(18, 18, 18)
                .addComponent(mostrarPrendas)
                .addGap(18, 18, 18)
                .addComponent(ordenarPrendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarPorColor)
                .addGap(18, 18, 18)
                .addComponent(totalPrendas)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearPrendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPrendasActionPerformed
        listaPrenda.add(new Prenda("Camiseta manga corta", 'S', "Blanco", 5.99));
        listaPrenda.add(new Prenda("Pantalón vaquero", 'M', "Azul medio", 30));
        listaPrenda.add(new Prenda("Camiseta dibujo", 'M', "Amarillo", 10));
        listaPrenda.add(new Prenda("Vestido largo flores", 'S', "Varios", 50));

        if (!listaPrenda.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Las prendas ya estan creadas");
            crearPrendas.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Prendas creadas");
        }
    }//GEN-LAST:event_crearPrendasActionPerformed

    private void mostrarPrendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPrendasActionPerformed
        listaPrendas.setModel(modeloLista);
        modeloLista.clear();

        modeloLista.addElement("DESCRIPCIÓN | TALLA | COLOE | PRECIO");
        for (Prenda lasPrendas : listaPrenda) {
            modeloLista.addElement(lasPrendas);

        }
    }//GEN-LAST:event_mostrarPrendasActionPerformed

    private void buscarPorColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorColorActionPerformed
        String prendaBuscar = JOptionPane.showInputDialog(null, "Introduce el color la prenda a buscar");
        modeloLista.clear();
        boolean encontrado = true;
        modeloLista.addElement("Prendas con el color: " + prendaBuscar);

        for (Prenda elColor : listaPrenda) {
            if (prendaBuscar.equalsIgnoreCase(elColor.getColor())) {
                modeloLista.addElement(elColor.getDescripcion());
                encontrado = false;
            }
        }

        if (encontrado) {
            modeloLista.addElement("Ninguna");
        }


    }//GEN-LAST:event_buscarPorColorActionPerformed

    private void totalPrendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPrendasActionPerformed
        int suma = 0;

        for (Prenda elPrice : listaPrenda) {
            suma += elPrice.getPrecio();
        }
        JOptionPane.showMessageDialog(null, "El total es de " + suma);
    }//GEN-LAST:event_totalPrendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Problema2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarPorColor;
    private javax.swing.JButton crearPrendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPrendas;
    private javax.swing.JButton mostrarPrendas;
    private javax.swing.JButton ordenarPrendas;
    private javax.swing.JButton totalPrendas;
    // End of variables declaration//GEN-END:variables
}
